### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by trondhindenes** [OctopusDeploy/OctopusDSC#138]
I'm getting a Installation of the Tentacle MSI failed; MSIEXEC exited with code: 1603. View the log at F:\octopus\logs\Tentacle.msi.log. In the log I can see this error: Error 1316. The specified account already exists

I have no idea what kind of account it's mentioning or anything.

The Octopus Tentacle remains unnecessary difficult to automate.

**Comment by stopthatastronaut** [comment]
Hey there. I'm looking into this now - do you have the complete log to send over by any chance? I'm looking into the error now and I'm finding a lot of references, but the root cause seems to differ, and the lines leading up to that particular error line vary spectacularly, so I'd like to try and narrow it down.

**Comment by stopthatastronaut** [comment]
The theme that keeps coming up in my research is a "corrupted registry", which is fairly vague I know, but Microsoft provide a tool which claims for fix various causes of this issue. 

https://support.microsoft.com/en-ca/help/17588/fix-problems-that-block-programs-from-being-installed-or-removed

I assume this is occuring on a pet server that's been around for a while? I'd be surprised to see it on a fresh install.

**Comment by trondhindenes** [comment]
We decided to just built our own - The DSC resource simply isn't robust enough.
choco install works fine, but since OctopusDSC forces the install of the tentacle its not possible to use it with an "externally" installed tentacle.
Looks to me like this DSC resource just tries to do way too much - installation, firewall rules etc, both of which are possible to do with other "native" DSC resources. IMHO OctopusDSC shouuld focus on  being a super-awesome-robust tool for configuring the Tentacle instance, and let other tooling do all the rest.

**Comment by stopthatastronaut** [comment]
I can see your point that `cTentacleAgent` does work that could _potentially_ be done in other ways, and that extra complexity can lead to problems.

However `cTentacleAgent` is literally designed to be a one-stop shop for installation and configuration of the Octopus Tentacle. To break that into separate components now would go against its original purpose and risk breaking backwards compatibility in a big way. 

I would like to know exactly what happened in your case, and to use that information make the resource more robust, however since the error is coming from msiexec, and we don't have logs or configuration info, we're somewhat limited in what we can do in response. 

We use cTentacleAgent every day, just like our customers, so it's very much in our own interest to make it as robust as we can, but without more information, there's very little we can do to progress this issue.

**Comment by trondhindenes** [comment]
That's bad news. I guess one option would be to implement a new "basic" dsc resource in order to keep backwards compatibility with the current (and at the same time remove the "c" moniker which was just a terrible idea from the get-go, but that's another story).

Our exact error can probably be observed by first installing the Tentacle using Chocolatey, and then applying the DSC resource.

**Comment by stopthatastronaut** [comment]
That 'c' thing, totally with you on it, but again, backwards compatibility. It was the recommendation from MS at the time the resource was released, for 'community' or 'contributior driven' resources, and if we change it now without doing a side-by-side resource (or some sort of aliasing trick), we risk breaking existing users.

If I've got time, I'll run up a basic repro of the chocolatey scenario in the next work week, see if I can reproduce. I've added a trello card to our internal board to remind me.

**Comment by pkatsourakis** [comment]
Sorry to bump an old issue, but I experience the same behavior. We have an internal chocolatey repo where we install the octopus tentacle, then run the DSC and get the 1603 error. 

Has anything been done on this for a fix or workaround?

**Suggestion:** 
Add a new ensure value such as "ConfirmPresent" that will only check that the tentacle is installed and not reinstall or upgrade. That allows users the flexibility to choose whether or not they want the DSC to manage installs while maintaining backwards compatibility.

**Comment by matt-richardson** [comment]
Can you let me know why you're using both choco and the DSC? If you skip using choco, then it should all be fine?

The comment by @stopthatastronaut still matches the current thinking

> [...] cTentacleAgent is literally designed to be a one-stop shop for installation and configuration of the Octopus Tentacle. To break that into separate components now would go against its original purpose and risk breaking backwards compatibility in a big way.

The DSC module isn't high on our priority list right now ([checkout the roadmap](https://octopus.com/company/roadmap) to see what we're focused on), so as there is a workaround here (dont use choco), then it's very unlikely we'll make any changes here any time soon.
