### ISSUE TITLE
Providing license key in HA setups

### ISSUE THREAD

**Issue by adhodgson1** [OctopusDeploy/OctopusDSC#140]
Hi,

I have a situation where I have 4 servers in a HA setup and the servers are being rebuilt.  I believe I am hitting an issue with Octopus where the license key is added using the configuration tool, but the server is hitting the maximum number of Octopus servers allowed.  Some of the nodes rebuild fine, but others hit this error:

message: The license could not be updated because the server is not compliant, so using the license would disable functionality.

For now I have disabled adding the license key via DSC to try and mitigate against this issue.

**Comment by adhodgson1** [comment]
Have had to revert this change providing a license key again because without it Octopus tries to register as the community edition.

**Comment by cvandal** [comment]
Hi @adhodgson1, this isn't an issue with OctopusDSC but rather that your license allows x number of nodes and as you're rebuilding, you haven't removed the old nodes which are now marked as offline and are still counted towards your total number of nodes. Having said that, there is work being done in Octopus so that offline nodes will not counted and this would fix your issue. There be an issue opened on Octopus very soon and I'll link it here.

**Comment by cvandal** [comment]
https://github.com/OctopusDeploy/Issues/issues/4668
