### ISSUE TITLE
PS gallery image having wrong hash value for version `4.0.384`

### ISSUE THREAD

**Issue by artisticcheese** [OctopusDeploy/OctopusDSC#156]
```
VERBOSE: DownloadPackage' - name='OctopusDSC', version='4.0.384',destination='C:\Users\gsuvalia\AppData\Local\Temp\111387500\OctopusDSC\OctopusDSC.nupkg', uri='https://www.powershellgallery.com/api/v2/package/OctopusDSC/4.0.384'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/OctopusDSC/4.0.384'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/OctopusDSC/4.0.384'.
VERBOSE: Completed downloading 'OctopusDSC'.
VERBOSE: Hash for package 'OctopusDSC' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='OctopusDSC', version='4.0.384',destination='C:\Users\gsuvalia\AppData\Local\Temp\111387500'
```

**Comment by matt-richardson** [comment]
Can you please provide some context about what command you are running?

Does this still install? Is it just a warning?

Looking at some of the spots where we are using DSC internally, it seems that most / all? instaslls show that message but still installs happily, eg:

```
VERBOSE: Hash for package 'cChoco' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='cChoco', version='2.3.1.0',destination='C:\Users\Administrator\AppData\Local\Temp\876097862'
VERBOSE: Catalog file 'cChoco.cat' is not found in the contents of the module 'cChoco' being installed.
VERBOSE: Module 'cChoco' was installed successfully to path 'C:\Program Files\WindowsPowerShell\Modules\cChoco\2.3.1.0'.
```

**Comment by artisticcheese** [comment]
Just simply installing via `Install-Module -name OctopusDSC -Repository PSgallery -Verbose -Force ` fails to install. I tried from pristine machines.

**Comment by stopthatastronaut** [comment]
I've tried installing 4.0.384 on a fresh Windows Server 2016 VM and I can see the verbose message, but it doesn't seem to impact installation at all, even with `-force` not specified. The same happens on 4.0.382. I see the message, but it has no impact on the installation.

In fact, it seems to be appearing on every package I try, whether published by us or not. This leads me to believe the problem is in the `PowerShellGet` module, or in the Powershell Gallery? I assume either the server is providing bad hashes, or the client is mis-hashing the local file during verification. Either way, I don't think it's anything we can influence, short of reporting it to Microsoft, so I'm going to close off this Issue pending any further developments
