### ISSUE TITLE
Tentacle drift detection

### ISSUE THREAD

**Issue by trondhindenes** [OctopusDeploy/OctopusDSC#48]
It seems that The resource will only update if `Ensure` is different from the current state (eg, install if missing).
It does not perform drift detection if for example if the value of `environment` has changed.

**Comment by matt-richardson** [comment]
This is [called out](https://github.com/OctopusDeploy/OctopusDSC/blob/master/README-cTentacleAgent.md#drift) in the readme. We know its not great, but we haven't had a change to look at it as yet.

I'll close this, and keep tracking it under #24, as the situation hasn't really changed since then.

**Comment by trondhindenes** [comment]
This might not be the place, but still: For a modern .Net based app, Tentacle is surprisingly hard to automate. Why not implement the administrative functions in a dll so that we can build robust powershell cmdlets on top? the tentacle.exe parameters are way under par in terms of automation.

**Comment by matt-richardson** [comment]
Hi @trondhindenes. Can you get in touch via our [support forum](https://octopus.com/support), so we can understand a bit better and hopefully assist here? 

We do all our automation of installs via the command line options, so it'd be great to understand where you see things are missing/difficult.

As for background, command line parameters are much more automatable from multiple languages than a dll, and as soon as you go "add a reference to this dll", you lose a big chunk of your audience. As it is, nearly everything that `Tentacle.exe` does is done via calls to the [OctopusClients](https://github.com/OctopusDeploy/OctopusClients) component, so that may be helpful?

**Comment by trondhindenes** [comment]
Well if you look at the code in the "new-tentacle":
```
else {
        Invoke-AndAssert { & .\tentacle.exe configure --instance $name --port $port --noListen "True" --console }
        $registerArguments += @("--comms-style", "TentacleActive",
                                "--server-comms-port", $serverPort)
    }
```

My point is just that by having to use an exe which takes a huge number of arguments, 80% of automation code is parsing arguments, escaping quotes, etc. Since there is a OctopusClient underneath, it would imho make so much more sense to build a robust PowerShell automation story directly on top of that instead of thru tentacle.exe.

Anyone who's worked extensively will agree that building powershell wrappers around old-school exe's is painful and error-prone.

Just my 5 cents.
