### ISSUE TITLE
SSL implementation seems incomplete

### ISSUE THREAD

**Issue by msnelling** [OctopusDeploy/OctopusDSC#52]
There doesn't seem to be an option to add an HTTPS listener to complement the ForceSSL option. Such an option should allow you to specify the certificate thumbprint as well as giving the option of creating a self-signed certificate.

**Comment by matt-richardson** [comment]
Thanks for the feedback, but this is not something we're likely to implement. This is actually related to `netsh` and the wider system, rather than something related specifically to Octopus.

It would be relatively simple to implement a `Script` resource that does it. In fact, here's a [great example](https://powershell.org/forums/topic/port-configuration-with-dsc/). Here's [another resource](http://mikefrobbins.com/2015/02/05/creating-a-desired-state-configuration-resource-for-self-signed-certificates/) that you could use to create the self signed cert.
