### ISSUE TITLE
Octopus Server resource only supports one instance

### ISSUE THREAD

**Issue by matt-richardson** [OctopusDeploy/OctopusDSC#54]
These bits are hardcoded for only one instance:
https://github.com/OctopusDeploy/OctopusDSC/blob/master/OctopusDSC/DSCResources/cOctopusServer/cOctopusServer.psm1#L683
https://github.com/OctopusDeploy/OctopusDSC/blob/master/OctopusDSC/DSCResources/cOctopusServer/cOctopusServer.psm1#L683

This bit implies it supports multiple instances:
https://github.com/OctopusDeploy/OctopusDSC/blob/master/README-cOctopusServer.md

We should make it support multiple instances

**Comment by michaelnoonan** [comment]
I've since discovered the other resources also have problems with using a non-default instance. For example, this line doesn't support the `--instance` argument and it fails with a pretty ugly error message which takes a while to understand the instance wasn't found: https://github.com/OctopusDeploy/OctopusDSC/blob/master/OctopusDSC/DSCResources/cOctopusServerUsernamePasswordAuthentication/cOctopusServerUsernamePasswordAuthentication.psm1#L88

```
VERBOSE: [MICHAELNOON1449]: LCM:  [ End    Test     ]  [[cOctopusServer]OctopusServer]  in 0.7230 seconds.
PowerShell DSC resource cOctopusServer  failed to execute Test-TargetResource functionality with error message: Invalid JSON primitive:
-------------------------------------------------------------------------------.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

VERBOSE: [MICHAELNOON1449]: LCM:  [ Start  Resource ]  [[cOctopusServerUsernamePasswordAuthentication]Enable Username/Password Auth]
VERBOSE: [MICHAELNOON1449]: LCM:  [ Start  Test     ]  [[cOctopusServerUsernamePasswordAuthentication]Enable Username/Password Auth]
Invalid JSON primitive: -------------------------------------------------------------------------------.
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
    + PSComputerName        : localhost
```
