### ISSUE TITLE
Feature request: add ServerThumbprint to cTentacleAgent

### ISSUE THREAD

**Issue by GavBurke** [OctopusDeploy/OctopusDSC#83]
Using the cTentacleAgent_ListeningTentacle.psm1 example for a server that is not publicly available does not work.

I require a way to run the tentacle listening configuration in the same way as the app does (where it DOES NOT register with Octopus), i.e. this script:

```
cd "C:\Program Files\Octopus Deploy\Tentacle"
Tentacle.exe create-instance --instance "Tentacle" --config "C:\Octopus\Tentacle.config" --console
Tentacle.exe new-certificate --instance "Tentacle" --if-blank --console
Tentacle.exe configure --instance "Tentacle" --reset-trust --console
Tentacle.exe configure --instance "Tentacle" --home "C:\Octopus" --app "C:\Octopus\Applications" --port "10933" --console
Tentacle.exe configure --instance "Tentacle" --trust "THUMPRINT_GOES_HERE" --console
netsh advfirewall firewall add rule "name=Octopus Deploy Tentacle" dir=in action=allow protocol=TCP localport=10933
Tentacle.exe service --instance "Tentacle" --install --start --console
```

**Comment by matt-richardson** [comment]
Have you tried setting the `RegisterWithServer` flag to `$false`? i.e. the same way [this test](https://github.com/OctopusDeploy/OctopusDSC/blob/master/Tests/Scenarios/Tentacle_Scenario_01_Install.ps1#L78) works?

**Comment by GavBurke** [comment]
Hi Matt

I didn’t see that listed anywhere in the example I had, I can give that a
shot but I’m doubtful as I do not see anywhere you are asking for the
server thumbprint??

Gavin

**Comment by matt-richardson** [comment]
At the moment, the resource does not support passing in the thumbprint. 

In the tests, we just execute [register-polling-tentacle.ps1](https://github.com/OctopusDeploy/OctopusDSC/blob/master/Tests/register-polling-tentacle.ps1) to register it with the server out of band. The scenario originally implemented was to support polling tentacles that are registered by another process - listening Tentacles that trust a specified thumbprint are not supported as yet by this approach.

You could use the `cTentacleAgent` DSC resource with the `RegisterWithServer` flag set to `$false`, and then use a script resource to configure the thumbprint directly.

It does sounds useful to have the ability to pass in the thumbprint, but at this point, it's unlikely to be implemented soon. That said, we will happily accept PRs.

**Comment by GavBurke** [comment]
Hi Matt

No worries thanks for confirming, I’ll pull the code and take a look as we
are needing that step for a large number of tentacles, and although it
works with the Script resource in DSC, it’d be great to have it all within
the one step.

Thanks again
Gavin

**Comment by matt-richardson** [comment]
I've renamed this issue to a feature request to add a property for the server thumbprint, to better reflect the desired outcome.

Let me know if you need any pointers for where to make the changes.

**Comment by matt-richardson** [comment]
Hi @GavBurke. I just had a deeper look at this, and it seems it is actually supported after all. You can pass `OctopusServerThumbprint` in, and it will [set the thumbprint](https://github.com/OctopusDeploy/OctopusDSC/blob/master/OctopusDSC/DSCResources/cTentacleAgent/cTentacleAgent.psm1#L509) as expected.

This is documented in the [cTentacleAgent readme](https://github.com/OctopusDeploy/OctopusDSC/blob/master/README-cTentacleAgent.md) (which I missed first go around myself). I guess the root misunderstanding is around the example you started from. That was just intended to be a relatively simple example to get you up and going, rather than a comprehensive overview of all params.

Do you have any suggestions on how we can make this easier?

**Comment by GavBurke** [comment]
Hi Matt

The example I started with was called "Listening Tentacle Example" but does
not match the behaviour of installing a listening tentacle via the MSI - no
server details other than thumprint is needed when using the MSI.

My suggestion to make things easier would be to have your Listening
Tentacle Example DSC script consistent with the behaviour of the MSI
install, that is specifying just the Octopus thumprint along with path for
instance files and deployed files (typically C:\Octopus and
C:\Octopus\Applications).

Regards
Gavin

**Comment by matt-richardson** [comment]
Hi @GavBurke 

The most common approach used is to automatically register with the server, rather than use some out-of-band mechanism for telling the server about the Tentacle, and as such, the example reflects that. While we could add extra examples, we would end up in a situation where it would be difficult to find the appropriate example.

Instead, I've updated the examples to include a link to the readme where it lists all properties.

I'm going to close this issue for now, as I think you're good to go.
